# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "aula-02" ]
  pull_request:
    branches: [ "aula-02" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Run Commands with a Secret
      run:  echo  "${{ secrets.CLIENT_TEST }}"
      env:
          SECRET_VALUE: "${{ secrets.CLIENT_TEST }}"
    
    - name: Print Secret Value here
      run: echo $SECRET_VALUE
          
    - name: build-BD
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Build
      run: go build -v main.go
